name: 10.02.lab01 deploy

on:
  push:
    branches: [feature/wf]
    paths: ["ch10/05-gallery/*.tf"]

  # 깃헙 웹사이트에 수동 배포 버튼
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  TF_VERSION: "1.14.7"
  AWS_REGION: "ap-northeast-2"
  WORKING_DIR: "ch10/05-gallery"

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_IAMROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Create Secrets Files
        run: |
          cat << 'EOF' > env.dev.tfvars
          ${{ secrets.DEV_TFVARS }}
          EOF

      - name: Terraform Init
        run: terraform init -input=false -backend-config="env.dev.backend.hcl"

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve -var-file="env.dev.tfvars" -no-color
      
      - name: Create Secrets Files
        run: |
          cat << 'EOF' > env.prod.tfvars
          ${{ secrets.PROD_TFVARS }}
          EOF

      - name: Terraform Init
        run: terraform init -input=false -backend-config="env.prod.backend.hcl" -reconfigure

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve -var-file="env.prod.tfvars" -no-color

